boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_wrapper.o: interrupt_wrapper.S
paging.o: paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
circular_buffer.o: circular_buffer.c circular_buffer.h types.h lib.h
ece391_fs.o: ece391_fs.c ece391_fs.h types.h lib.h
fs.o: fs.c fs.h ece391_fs.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt.o: interrupt.c interrupt.h types.h lib.h terminal.h x86_desc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  ece391_fs.h terminal.h interrupt.h syscall.h rtc.h
lib.o: lib.c lib.h types.h terminal.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h x86_desc.h interrupt.h
syscall.o: syscall.c syscall.h interrupt.h types.h
terminal.o: terminal.c circular_buffer.h types.h terminal.h \
  keyboard_map.h i8259.h lib.h x86_desc.h
